server:
  port: 8282

spring:
  application:
    name: recommendation_service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: book-group-id
      auto-offset-reset: earliest